### ISSUE TITLE
No main class or java file ?

### ISSUE THREAD

**Issue by Mr-Kumar-Abhishek** [ronz94/Steadfast#1]
Regarding this commit --> [a97ebeab46d378ff4aa70c6c147ba2aa18a509db](https://github.com/ronz94/Steadfast/commit/a97ebeab46d378ff4aa70c6c147ba2aa18a509db)

It could be seen that there are no java files after this commit, and the commit is of changing the main class.
Given that you were changing the main class to something. And also the name of the file which contains the java source code... use command `git mv old_filename.java new_file.java` or atleast add the untracked files (which is the same file with a new name, if you have changed from eclipse maybe ?) and then commit.

To fix this use `git reset --soft HEAD~1` , and then add untracked files, commit and force push, `git push -f origin skeleton`

example for undoing a commit locally:

```
$ git commit ...              (1)
$ git reset --soft HEAD~1     (2)
<< edit files as necessary >> (3)
$ git add ....                (4)
$ git commit -c ORIG_HEAD     (5)
```

**Comment by ronz94** [comment]
Fixed this issue with this commit https://github.com/ronz94/Steadfast/commit/ff59c4f77ee63c28a001db019583dfb826a7d38e
