### ISSUE TITLE
using package keyword for built in packages ??

### ISSUE THREAD

**Issue by Mr-Kumar-Abhishek** [ronz94/Steadfast#2]
regarding this commit --> https://github.com/ronz94/Steadfast/commit/73660ca929f828a948acf83febc5589b890340db

```
package javax.swing;


import java.awt.FlowLayout; //For defining the layout
import java.awt.event.ActionListener;
import java.io.*; // input-output operations
import java.net.HttpURLConnection; // making a connection
import java.net.URL; // in making a URL object
import javax.swing.JFrame; // in making Swing Frame
import javax.swing.JProgressBar; // in implementing Progress Bar
import java.awt.event.*;
```

We don't usually use `package` keyword for built in packages. Any special reason to do this ? Also if you are doing this, please remove all the imports of swing below it. And maybe also include all the files and libraries of swing package in the commit ? unless otherwise it doesn't makes sense.

**Comment by ronz94** [comment]
without creating this package,'import javax.swing' was giving errors!

**Comment by Mr-Kumar-Abhishek** [comment]
It would be more helpfull for all of us if you just tell what are the errors rather than blankly telling , it is giving 'errors'.

**Comment by Mr-Kumar-Abhishek** [comment]
Also, if you think you need this as `package javax.swing;`  then remove the imports having `javax.swing`

**Comment by ronz94** [comment]
Removed unnecessary imports. 
https://github.com/ronz94/Steadfast/commit/44d7cb52d099f6fce80c95a2bf2f21e025778826
