### ISSUE TITLE
Two files having same class and filename, 'Steadfast' and 'Steadfast.java' ?

### ISSUE THREAD

**Issue by Mr-Kumar-Abhishek** [ronz94/Steadfast#4]
After this commit :- https://github.com/ronz94/Steadfast/commit/73660ca929f828a948acf83febc5589b890340db

There are two files with same class name and filenname `Steadfast.java`. Need to remove one of them. This basically [depends](https://github.com/ronz94/Steadfast/issues/2) on whether you are using `package` keyword for including swing or not.

First file path: `/src/Steadfast.java`
Second file path: `src/javax/swing/Steadfast.java`

we need only one.

**Comment by ronz94** [comment]
we have to keep the 2nd one and remove the 1st file path.

**Comment by Mr-Kumar-Abhishek** [comment]
Yes, well delete the first file then, commit and close this issue.

**Comment by ronz94** [comment]
unused file deleted.
