### ISSUE TITLE
progress bar is not working.

### ISSUE THREAD

**Issue by Mr-Kumar-Abhishek** [ronz94/Steadfast#8]
After resolving of issue #7 , progress bar is not working, found after commit:-  96d3c90

**Comment by Mr-Kumar-Abhishek** [comment]
This issue is resolved with this commit:- eb0ec3258b2e277dd42ca1bb75822a0ae4535a48 
Please re-check it's functionality and close this issue.

**Comment by ronz94** [comment]
functionality rechecked. all working fine.
